---
name: CI

on:
  pull_request:

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Copy linter settings
        run: |
          mkdir .github/linters
          cp .htmlhintrc .github/linters/
          cp .dockerfilelintrc .github/linters/

      - name: Lint Code Base
        uses: github/super-linter@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  rubocop:
    needs: lint
    name: Rubocop Analysis
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install Code Scanning integration
        run: bundle add code-scanning-rubocop --version 0.3.0 --skip-install

      - name: Install dependencies
        run: bundle install

      - name: Rubocop run
        run: |
          bash -c "
            bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
            [[ $? -ne 2 ]]
          "

      - name: Upload Sarif output
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: rubocop.sarif
